name: Scheduled Vulnerability Scans

on:
    schedule:
        - cron: '0 2 * * *'

jobs:
    trigger-vulnerability-scan-5_2_z:
        strategy:
            matrix:
                ref: [ '5.2.z', '5.1.z', '5.0.z', '4.2.z' ]
        uses: ./.github/workflows/vulnerability_scan_subworkflow.yml
        with:
            ref: ${{ matrix.ref }}
            